export interface QuestionCategory {
  title: string;
  questions: string[];
}

export const questionsData: QuestionCategory[] = [
  {
    title: 'Questions sur la croyance',
    questions: [
      'Qui est Allah ?',
      'Quels sont les attributs d\'Allah ?',
      'Que signifie « Il n\'y a de divinité digne d\'adoration qu\'Allah » ?',
      'Pourquoi devons-nous adorer uniquement Allah ?',
      'Qu\'est-ce que le Tawhid (l\'unicité d\'Allah) ?',
      'Quels sont les piliers de la foi (Iman) ?',
      'Qu\'est-ce que le destin (Qadar) ?',
      'Qu\'est-ce que le Shirk (l\'association) et pourquoi est-il interdit ?',
      'Qu\'est-ce que l\'innovation (Bid\'ah) en Islam ?',
      'Comment renforcer sa foi au quotidien ?',
    ],
  },
  {
    title: 'Questions sur les pratiques religieuses',
    questions: [
      'Quels sont les piliers de l\'Islam ?',
      'Comment effectuer correctement la prière (Salat) ?',
      'Qu\'est-ce qui annule les ablutions (Wudu) ?',
      'Quand peut-on raccourcir ou combiner les prières ?',
      'Qu\'est-ce que le jeûne du mois de Ramadan ?',
      'Quelles sont les conditions de validité du jeûne ?',
      'Qu\'est-ce que la Zakat (l\'aumône obligatoire) ?',
      'Qui doit payer la Zakat et comment la calculer ?',
      'Qu\'est-ce que le Hajj (le pèlerinage) ?',
      'Quelles sont les conditions pour accomplir le Hajj ?',
    ],
  },
  {
    title: 'Questions sur la famille et la vie sociale',
    questions: [
      'Quels sont les droits des parents en Islam ?',
      'Quel est le rôle de la mère en Islam ?',
      'Comment traiter ses voisins selon l\'Islam ?',
      'Qu\'est-ce que la bienveillance (Ihsan) envers les autres ?',
      'Quels sont les droits et devoirs du mari et de la femme ?',
      'Comment éduquer les enfants selon les enseignements islamiques ?',
      'Quelles sont les règles du mariage en Islam ?',
      'Qu\'est-ce que la dot (Mahr) ?',
      'Comment gérer les conflits familiaux selon l\'Islam ?',
      'Qu\'est-ce que le respect des aînés en Islam ?',
    ],
  },
  {
    title: 'Questions sur l\'au-delà',
    questions: [
      'Qu\'est-ce que la mort en Islam ?',
      'Que se passe-t-il dans la tombe (Barzakh) ?',
      'Qu\'est-ce que le Jour du Jugement (Yawm al-Qiyamah) ?',
      'Qu\'est-ce que le Paradis (Jannah) ?',
      'Qu\'est-ce que l\'Enfer (Jahannam) ?',
      'Qui entrera au Paradis ?',
      'Comment se préparer à l\'au-delà ?',
      'Qu\'est-ce que la Balance (Mizan) ?',
      'Qu\'est-ce que le Pont (Sirat) ?',
      'Qu\'est-ce que l\'intercession (Shafa\'ah) du Prophète Muhammad (ﷺ) ?',
    ],
  },
  {
    title: 'Questions sur les prophètes et les compagnons',
    questions: [
      'Qui est le Prophète Muhammad (ﷺ) ?',
      'Quels sont les miracles du Prophète Muhammad (ﷺ) ?',
      'Qui sont les compagnons (Sahaba) ?',
      'Qui sont les quatre califes bien guidés ?',
      'Quelle est l\'importance de suivre la Sunnah ?',
      'Qui sont les prophètes mentionnés dans le Coran ?',
      'Qu\'est-ce que le voyage nocturne (Isra et Mi\'raj) ?',
      'Quel est le rôle de Jibril (Gabriel) ?',
      'Qui sont les meilleures femmes en Islam ?',
      'Qu\'est-ce que la biographie (Sira) du Prophète ?',
    ],
  },
  {
    title: 'Questions sur le Coran',
    questions: [
      'Qu\'est-ce que le Coran ?',
      'Comment le Coran a-t-il été révélé ?',
      'Quelle est la différence entre le Coran et la Sunnah ?',
      'Comment apprendre à lire le Coran ?',
      'Quelle est la récompense de lire le Coran ?',
      'Qu\'est-ce que le Tafsir (l\'exégèse du Coran) ?',
      'Quelles sont les sourates les plus importantes du Coran ?',
      'Comment mémoriser le Coran (Hifz) ?',
      'Quelles sont les règles de récitation du Coran (Tajweed) ?',
      'Peut-on toucher le Coran sans ablutions ?',
    ],
  },
  {
    title: 'Questions sur l\'éthique et le comportement',
    questions: [
      'Qu\'est-ce que la sincérité (Ikhlas) en Islam ?',
      'Comment purifier son cœur ?',
      'Qu\'est-ce que la patience (Sabr) ?',
      'Comment gérer la colère selon l\'Islam ?',
      'Qu\'est-ce que l\'humilité en Islam ?',
      'Comment éviter la médisance (Ghiba) ?',
      'Qu\'est-ce que la jalousie (Hasad) et comment la combattre ?',
      'Comment être reconnaissant envers Allah ?',
      'Qu\'est-ce que la véracité (Sidq) ?',
      'Comment améliorer son caractère (Akhlaq) ?',
    ],
  },
  {
    title: 'Questions sur les interdictions',
    questions: [
      'Pourquoi le porc est-il interdit en Islam ?',
      'Pourquoi l\'alcool est-il interdit ?',
      'Qu\'est-ce que le Riba (l\'usure) ?',
      'Pourquoi le mensonge est-il un grand péché ?',
      'Qu\'est-ce que la médisance et pourquoi est-elle interdite ?',
      'Pourquoi les jeux de hasard sont-ils interdits ?',
      'Qu\'est-ce que la fornication (Zina) et ses conséquences ?',
      'Pourquoi la musique est-elle débattue en Islam ?',
      'Qu\'est-ce que l\'oppression (Dhulm) ?',
      'Comment éviter les péchés majeurs ?',
    ],
  },
  {
    title: 'LES QUESTIONS NON DÉFINIES ET SUJETS DE DIVERGENCE EN ISLAM',
    questions: [
      'Qu\'est-ce qu\'une question non définie en Islam ?',
      'Pourquoi existe-t-il des divergences d\'opinions parmi les savants ?',
      'Comment gérer les sujets sur lesquels il n\'y a pas de consensus clair ?',
      'Quelle est la différence entre une divergence légitime et une innovation (Bid\'ah) ?',
      'Quels sont les sujets de divergence les plus courants en Islam ?',
      'Comment respecter les différentes écoles de pensée (Madhahib) ?',
      'Qu\'est-ce que l\'Ijtihad (l\'effort d\'interprétation) ?',
      'Qui peut pratiquer l\'Ijtihad et dans quelles circonstances ?',
      'Comment un musulman ordinaire doit-il se comporter face aux divergences ?',
      'Qu\'est-ce que le Taqlid (suivre un savant) et est-il obligatoire ?',
      'Les divergences sur les questions secondaires (Furu\') affectent-elles la foi ?',
      'Comment distinguer entre les questions fondamentales et secondaires ?',
      'Qu\'est-ce que le principe de la facilité (Yusur) dans les questions divergentes ?',
      'Les quatre écoles sunnites (Hanafi, Maliki, Shafi\'i, Hanbali) sont-elles toutes valides ?',
      'Comment éviter le fanatisme envers une école particulière ?',
    ],
  },
];
