export interface Dua {
  id: string;
  category: string;
  title: string;
  arabicText: string;
  englishText: string;
  frenchText: string;
  transliteration: string;
  reference: string;
  repetitions: number;
}

export const FALLBACK_DUAS: Record<string, Dua[]> = {
  morning: [
    {
      id: 'morning-1',
      category: 'morning',
      title: 'Dhikr du matin - Ayat al-Kursi',
      arabicText: 'اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ ۚ لَهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ ۗ مَنْ ذَا الَّذِي يَشْفَعُ عِنْدَهُ إِلَّا بِإِذْنِهِ ۚ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ ۖ وَلَا يُحِيطُونَ بِشَيْءٍ مِنْ عِلْمِهِ إِلَّا بِمَا شَاءَ ۚ وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالْأَرْضَ ۖ وَلَا يَئُودُهُ حِفْظُهُمَا ۚ وَهُوَ الْعَلِيُّ الْعَظِيمُ',
      englishText: 'Allah - there is no deity except Him, the Ever-Living, the Self-Sustaining. Neither drowsiness overtakes Him nor sleep. To Him belongs whatever is in the heavens and whatever is on the earth. Who is it that can intercede with Him except by His permission? He knows what is before them and what will be after them, and they encompass not a thing of His knowledge except for what He wills. His Kursi extends over the heavens and the earth, and their preservation tires Him not. And He is the Most High, the Most Great.',
      frenchText: "Allah ! Point de divinit\u00e9 \u00e0 part Lui, le Vivant, Celui qui subsiste par Lui-m\u00eame. Ni somnolence ni sommeil ne Le saisissent. A Lui appartient tout ce qui est dans les cieux et sur la terre. Qui peut interceder aupr\u00e8s de Lui sans Sa permission ? Il connait leur pass\u00e9 et leur futur. Et de Sa science, ils n'embrassent que ce qu'Il veut. Son Tr\u00f4ne d\u00e9borde les cieux et la terre, dont la garde ne Lui co\u00fbte aucune peine. Et Il est le Tr\u00e8s Haut, le Tr\u00e8s Grand.",
      transliteration: "Allaahu laa ilaaha illaa Huwal-Hayyul-Qayyoom. Laa ta'khudhuhu sinatun wa laa nawm. Lahu maa fis-samaawaati wa maa fil-ard. Man dhal-ladhee yashfa'u 'indahu illaa bi-idhnih. Ya'lamu maa bayna aydeehim wa maa khalfahum. Wa laa yuheetoona bi shay'in min 'ilmihi illaa bimaa shaa'. Wasi'a kursiyyuhus-samaawaati wal-ard. Wa laa ya'ooduhu hifdhuhumaa. Wa Huwal-'Aliyyul-'Adheem.",
      reference: 'Coran 2:255',
      repetitions: 1,
    },
    {
      id: 'morning-2',
      category: 'morning',
      title: "Dou'a du matin - Protection",
      arabicText: 'أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ',
      englishText: 'We have reached the morning and at this very time the whole kingdom belongs to Allah. All praise is for Allah. None has the right to be worshipped except Allah alone, without any partner. To Him belongs the dominion, and to Him belongs all praise, and He is over all things capable.',
      frenchText: "Nous voil\u00e0 au matin et le royaume appartient \u00e0 Allah. Louange \u00e0 Allah. Nul ne m\u00e9rite d'\u00eatre ador\u00e9 sauf Allah, Unique, sans associ\u00e9. A Lui la royaut\u00e9, \u00e0 Lui la louange et Il est capable de toute chose.",
      transliteration: "Asbahnaa wa asbahal-mulku lillaah, walhamdu lillaah, laa ilaaha illallaahu wahdahu laa shareeka lah, lahul-mulku wa lahul-hamdu wa Huwa 'alaa kulli shay'in Qadeer.",
      reference: 'Sahih Muslim 2723',
      repetitions: 1,
    },
    {
      id: 'morning-3',
      category: 'morning',
      title: "Dou'a du matin - Seigneur des mondes",
      arabicText: 'اللَّهُمَّ بِكَ أَصْبَحْنَا، وَبِكَ أَمْسَيْنَا، وَبِكَ نَحْيَا، وَبِكَ نَمُوتُ وَإِلَيْكَ النُّشُورُ',
      englishText: 'O Allah, by Your leave we have reached the morning and by Your leave we have reached the evening, by Your leave we live and die and unto You is our resurrection.',
      frenchText: "\u00d4 Allah, c'est par Toi que nous sommes arriv\u00e9s au matin et c'est par Toi que nous sommes arriv\u00e9s au soir. C'est par Toi que nous vivons et mourons, et vers Toi est la r\u00e9surrection.",
      transliteration: "Allaahumma bika asbahnaa, wa bika amsaynaa, wa bika nahyaa, wa bika namootu wa ilaykan-nushoor.",
      reference: 'Sunan at-Tirmidhi 3391',
      repetitions: 1,
    },
    {
      id: 'morning-4',
      category: 'morning',
      title: 'Sayyid al-Istighfar',
      arabicText: 'اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَهَ إِلَّا أَنْتَ خَلَقْتَنِي وَأَنَا عَبْدُكَ وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ وَأَبُوءُ بِذَنْبِي فَاغْفِرْ لِي فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ',
      englishText: "O Allah, You are my Lord, none has the right to be worshipped except You. You created me and I am Your servant, and I abide by Your covenant and promise as best I can. I seek refuge in You from the evil of what I have done. I acknowledge Your favour upon me and I acknowledge my sin, so forgive me, for verily none can forgive sins except You.",
      frenchText: "\u00d4 Allah, Tu es mon Seigneur, nul ne m\u00e9rite d'\u00eatre ador\u00e9 sauf Toi. Tu m'as cr\u00e9\u00e9 et je suis Ton serviteur, et je me conforme \u00e0 Ton pacte et \u00e0 Ta promesse autant que je le peux. Je cherche refuge aupr\u00e8s de Toi contre le mal que j'ai commis. Je reconnais Ton bienfait envers moi et je reconnais mon p\u00e9ch\u00e9, pardonne-moi donc, car nul ne pardonne les p\u00e9ch\u00e9s sauf Toi.",
      transliteration: "Allaahumma Anta Rabbee laa ilaaha illaa Anta, khalaqtanee wa ana 'abduka, wa ana 'alaa 'ahdika wa wa'dika mastata't. A'oodhu bika min sharri maa sana't. Aboo'u laka bini'matika 'alayya, wa aboo'u bidhanbee, faghfir lee, fa innahu laa yaghfirudh-dhunooba illaa Ant.",
      reference: 'Sahih al-Bukhari 6306',
      repetitions: 1,
    },
    {
      id: 'morning-5',
      category: 'morning',
      title: 'SubhanAllah wa bihamdihi',
      arabicText: 'سُبْحَانَ اللَّهِ وَبِحَمْدِهِ',
      englishText: 'Glory is to Allah and praise is to Him.',
      frenchText: "Gloire \u00e0 Allah et louange \u00e0 Lui.",
      transliteration: 'SubhaanAllaahi wa bihamdihi.',
      reference: 'Sahih Muslim 2692',
      repetitions: 100,
    },
  ],
  evening: [
    {
      id: 'evening-1',
      category: 'evening',
      title: "Dou'a du soir - Entree dans la soiree",
      arabicText: 'أَمْسَيْنَا وَأَمْسَى الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ',
      englishText: 'We have reached the evening and at this very time the whole kingdom belongs to Allah. All praise is for Allah. None has the right to be worshipped except Allah alone, without any partner.',
      frenchText: "Nous voil\u00e0 au soir et le royaume appartient \u00e0 Allah. Louange \u00e0 Allah. Nul ne m\u00e9rite d'\u00eatre ador\u00e9 sauf Allah, Unique, sans associ\u00e9.",
      transliteration: "Amsaynaa wa amsal-mulku lillaah, walhamdu lillaah, laa ilaaha illallaahu wahdahu laa shareeka lah, lahul-mulku wa lahul-hamdu wa Huwa 'alaa kulli shay'in Qadeer.",
      reference: 'Sahih Muslim 2723',
      repetitions: 1,
    },
    {
      id: 'evening-2',
      category: 'evening',
      title: "Dou'a du soir - Refuge",
      arabicText: 'اللَّهُمَّ بِكَ أَمْسَيْنَا، وَبِكَ أَصْبَحْنَا، وَبِكَ نَحْيَا، وَبِكَ نَمُوتُ وَإِلَيْكَ الْمَصِيرُ',
      englishText: 'O Allah, by Your leave we have reached the evening and by Your leave we have reached the morning, by Your leave we live and die and unto You is our return.',
      frenchText: "\u00d4 Allah, c'est par Toi que nous sommes arriv\u00e9s au soir et c'est par Toi que nous sommes arriv\u00e9s au matin. C'est par Toi que nous vivons et mourons, et vers Toi est le retour.",
      transliteration: "Allaahumma bika amsaynaa, wa bika asbahnaa, wa bika nahyaa, wa bika namootu wa ilaykal-maseer.",
      reference: 'Sunan at-Tirmidhi 3391',
      repetitions: 1,
    },
    {
      id: 'evening-3',
      category: 'evening',
      title: 'Sourate Al-Ikhlas',
      arabicText: 'قُلْ هُوَ اللَّهُ أَحَدٌ ۝ اللَّهُ الصَّمَدُ ۝ لَمْ يَلِدْ وَلَمْ يُولَدْ ۝ وَلَمْ يَكُن لَّهُ كُفُوًا أَحَدٌ',
      englishText: 'Say, "He is Allah, [who is] One, Allah, the Eternal Refuge. He neither begets nor is born, nor is there to Him any equivalent."',
      frenchText: "Dis : \"Il est Allah, Unique. Allah, Le Seul \u00e0 \u00eatre implor\u00e9 pour ce que nous d\u00e9sirons. Il n'a jamais engendr\u00e9, ni n'a \u00e9t\u00e9 engendr\u00e9. Et nul n'est \u00e9gal \u00e0 Lui.\"",
      transliteration: "Qul huwallaahu ahad. Allaahus-samad. Lam yalid wa lam yoolad. Wa lam yakul-lahu kufuwan ahad.",
      reference: 'Coran 112:1-4',
      repetitions: 3,
    },
  ],
  after_salah: [
    {
      id: 'after_salah-1',
      category: 'after_salah',
      title: "Apres la priere - Istighfar",
      arabicText: 'أَسْتَغْفِرُ اللَّهَ',
      englishText: 'I seek the forgiveness of Allah.',
      frenchText: "Je demande pardon \u00e0 Allah.",
      transliteration: 'Astaghfirullaah.',
      reference: 'Sahih Muslim 591',
      repetitions: 3,
    },
    {
      id: 'after_salah-2',
      category: 'after_salah',
      title: 'Apres la priere - Tasbih',
      arabicText: 'سُبْحَانَ اللَّهِ وَالْحَمْدُ لِلَّهِ وَاللَّهُ أَكْبَرُ',
      englishText: 'Glory is to Allah, praise is to Allah, and Allah is the Greatest.',
      frenchText: "Gloire \u00e0 Allah, louange \u00e0 Allah, et Allah est le Plus Grand.",
      transliteration: 'SubhaanAllaah, walhamdu lillaah, wallaahu Akbar.',
      reference: 'Sahih Muslim 595',
      repetitions: 33,
    },
    {
      id: 'after_salah-3',
      category: 'after_salah',
      title: 'Apres la priere - Tahlil',
      arabicText: 'لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ',
      englishText: 'None has the right to be worshipped except Allah, alone, without partner. To Him belongs all sovereignty and praise and He is over all things omnipotent.',
      frenchText: "Nul ne m\u00e9rite d'\u00eatre ador\u00e9 sauf Allah, Seul, sans associ\u00e9. A Lui la royaut\u00e9, \u00e0 Lui la louange et Il est Omnipotent.",
      transliteration: "Laa ilaaha illallaahu wahdahu laa shareeka lah, lahul-mulku wa lahul-hamdu wa Huwa 'alaa kulli shay'in Qadeer.",
      reference: 'Sahih al-Bukhari 6330',
      repetitions: 1,
    },
  ],
  sleep: [
    {
      id: 'sleep-1',
      category: 'sleep',
      title: "Dou'a avant de dormir",
      arabicText: 'بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا',
      englishText: 'In Your name O Allah, I live and die.',
      frenchText: "En Ton nom, \u00f4 Allah, je meurs et je vis.",
      transliteration: 'Bismikallahumma amootu wa ahyaa.',
      reference: 'Sahih al-Bukhari 6324',
      repetitions: 1,
    },
    {
      id: 'sleep-2',
      category: 'sleep',
      title: 'Sourate Al-Mulk avant de dormir',
      arabicText: 'تَبَارَكَ الَّذِي بِيَدِهِ الْمُلْكُ وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ',
      englishText: 'Blessed is He in whose hand is dominion, and He is over all things competent.',
      frenchText: "B\u00e9ni soit Celui dans la main de qui est la royaut\u00e9, et Il est Omnipotent.",
      transliteration: "Tabaarakal-ladhee biyadihil-mulku wa Huwa 'alaa kulli shay'in Qadeer.",
      reference: 'Coran 67:1 - Sunan at-Tirmidhi 2891',
      repetitions: 1,
    },
    {
      id: 'sleep-3',
      category: 'sleep',
      title: "Dou'a de protection pendant le sommeil",
      arabicText: 'اللَّهُمَّ قِنِي عَذَابَكَ يَوْمَ تَبْعَثُ عِبَادَكَ',
      englishText: 'O Allah, protect me from Your punishment on the Day You resurrect Your servants.',
      frenchText: "\u00d4 Allah, prot\u00e8ge-moi de Ton ch\u00e2timent le Jour o\u00f9 Tu ressusciteras Tes serviteurs.",
      transliteration: "Allaahumma qinee 'adhaabaka yawma tab'athu 'ibaadak.",
      reference: 'Sunan Abu Dawud 5045',
      repetitions: 3,
    },
  ],
  travel: [
    {
      id: 'travel-1',
      category: 'travel',
      title: "Dou'a du voyage",
      arabicText: 'سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ وَإِنَّا إِلَى رَبِّنَا لَمُنْقَلِبُونَ',
      englishText: 'Glory to Him who has subjected this to us, and we could never have it (by our efforts). And verily, to our Lord we shall return.',
      frenchText: "Gloire \u00e0 Celui qui nous a soumis tout cela alors que nous n'\u00e9tions pas capables de les dominer. Et c'est vers notre Seigneur que nous retournerons.",
      transliteration: "Subhaanal-ladhee sakhkhara lanaa haadha wa maa kunnaa lahu muqrineen. Wa innaa ilaa Rabbinaa lamunqaliboon.",
      reference: 'Coran 43:13-14',
      repetitions: 1,
    },
    {
      id: 'travel-2',
      category: 'travel',
      title: "Dou'a d'entree dans une ville",
      arabicText: 'اللَّهُمَّ رَبَّ السَّمَاوَاتِ السَّبْعِ وَمَا أَظْلَلْنَ وَرَبَّ الأَرَضِينَ السَّبْعِ وَمَا أَقْلَلْنَ وَرَبَّ الشَّيَاطِينِ وَمَا أَضْلَلْنَ وَرَبَّ الرِّيَاحِ وَمَا ذَرَيْنَ أَسْأَلُكَ خَيْرَ هَذِهِ الْقَرْيَةِ وَخَيْرَ أَهْلِهَا وَأَعُوذُ بِكَ مِنْ شَرِّهَا وَشَرِّ أَهْلِهَا وَشَرِّ مَا فِيهَا',
      englishText: 'O Allah, Lord of the seven heavens and all that they envelop, Lord of the seven earths and all that they carry, Lord of the devils and all whom they misguide, Lord of the winds and all whom they whisk away. I ask You for the goodness of this village and the goodness of its people, and I seek refuge in You from its evil and the evil of its people and the evil that is within it.',
      frenchText: "\u00d4 Allah, Seigneur des sept cieux et de tout ce qu'ils couvrent, Seigneur des sept terres et de tout ce qu'elles portent, Seigneur des d\u00e9mons et de tous ceux qu'ils \u00e9garent, Seigneur des vents et de tout ce qu'ils emportent. Je Te demande le bien de cette ville et le bien de ses habitants, et je cherche refuge aupr\u00e8s de Toi contre son mal, le mal de ses habitants et le mal qui s'y trouve.",
      transliteration: "Allaahumma Rabbas-samaawaatis-sab'i wa maa adhlalna, wa Rabbal-aradeenas-sab'i wa maa aqlalna, wa Rabbash-shayaateeni wa maa adhlalna, wa Rabbar-riyaahi wa maa dharayna. As'aluka khayra haadhihil-qaryati wa khayra ahlihaa, wa a'oodhu bika min sharrihaa wa sharri ahlihaa wa sharri maa feehaa.",
      reference: "Mustadrak al-Hakim 2/100, Ibn as-Sunni 524",
      repetitions: 1,
    },
  ],
  food: [
    {
      id: 'food-1',
      category: 'food',
      title: 'Avant de manger',
      arabicText: 'بِسْمِ اللَّهِ',
      englishText: 'In the name of Allah.',
      frenchText: "Au nom d'Allah.",
      transliteration: 'Bismillaah.',
      reference: 'Sahih al-Bukhari 5376',
      repetitions: 1,
    },
    {
      id: 'food-2',
      category: 'food',
      title: "Apres avoir mange",
      arabicText: 'الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنِي هَذَا وَرَزَقَنِيهِ مِنْ غَيْرِ حَوْلٍ مِنِّي وَلَا قُوَّةٍ',
      englishText: 'Praise is to Allah who has fed me this and provided it for me without any power or might from myself.',
      frenchText: "Louange \u00e0 Allah qui m'a nourri de ceci et me l'a accord\u00e9 sans force ni puissance de ma part.",
      transliteration: "Alhamdu lillaahil-ladhee at'amanee haadhaa wa razaqaneehi min ghayri hawlin minnee wa laa quwwah.",
      reference: 'Sunan at-Tirmidhi 3458',
      repetitions: 1,
    },
    {
      id: 'food-3',
      category: 'food',
      title: "Dou'a en cas d'oubli de Bismillah",
      arabicText: 'بِسْمِ اللَّهِ أَوَّلَهُ وَآخِرَهُ',
      englishText: 'In the name of Allah at its beginning and at its end.',
      frenchText: "Au nom d'Allah \u00e0 son d\u00e9but et \u00e0 sa fin.",
      transliteration: 'Bismillaahi awwalahu wa aakhirah.',
      reference: 'Sunan Abu Dawud 3767',
      repetitions: 1,
    },
  ],
  protection: [
    {
      id: 'protection-1',
      category: 'protection',
      title: "Dou'a de protection contre le mal",
      arabicText: 'أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ',
      englishText: 'I seek refuge in the perfect words of Allah from the evil of what He has created.',
      frenchText: "Je cherche refuge dans les paroles parfaites d'Allah contre le mal de ce qu'Il a cr\u00e9\u00e9.",
      transliteration: "A'oodhu bikalimaatillaahit-taammaati min sharri maa khalaq.",
      reference: 'Sahih Muslim 2708',
      repetitions: 3,
    },
    {
      id: 'protection-2',
      category: 'protection',
      title: 'Les deux sourates protectrices - Al-Falaq',
      arabicText: 'قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ ۝ مِنْ شَرِّ مَا خَلَقَ ۝ وَمِنْ شَرِّ غَاسِقٍ إِذَا وَقَبَ ۝ وَمِنْ شَرِّ النَّفَّاثَاتِ فِي الْعُقَدِ ۝ وَمِنْ شَرِّ حَاسِدٍ إِذَا حَسَدَ',
      englishText: 'Say, "I seek refuge in the Lord of daybreak, from the evil of that which He created, and from the evil of darkness when it settles, and from the evil of the blowers in knots, and from the evil of an envier when he envies."',
      frenchText: "Dis : \"Je cherche protection aupr\u00e8s du Seigneur de l'aube naissante, contre le mal des \u00eatres qu'Il a cr\u00e9\u00e9s, contre le mal de l'obscurit\u00e9 quand elle s'approfondit, contre le mal de celles qui soufflent sur les noeuds, et contre le mal de l'envieux quand il envie.\"",
      transliteration: "Qul a'oodhu birabbil-falaq. Min sharri maa khalaq. Wa min sharri ghaasiqin idhaa waqab. Wa min sharrin-naffaathaati fil-'uqad. Wa min sharri haasidin idhaa hasad.",
      reference: 'Coran 113:1-5',
      repetitions: 3,
    },
    {
      id: 'protection-3',
      category: 'protection',
      title: 'Sourate An-Nas',
      arabicText: 'قُلْ أَعُوذُ بِرَبِّ النَّاسِ ۝ مَلِكِ النَّاسِ ۝ إِلَٰهِ النَّاسِ ۝ مِنْ شَرِّ الْوَسْوَاسِ الْخَنَّاسِ ۝ الَّذِي يُوَسْوِسُ فِي صُدُورِ النَّاسِ ۝ مِنَ الْجِنَّةِ وَالنَّاسِ',
      englishText: 'Say, "I seek refuge in the Lord of mankind, the Sovereign of mankind, the God of mankind, from the evil of the retreating whisperer, who whispers in the breasts of mankind, among jinn and among mankind."',
      frenchText: "Dis : \"Je cherche protection aupr\u00e8s du Seigneur des hommes, le Souverain des hommes, Dieu des hommes, contre le mal du mauvais conseiller, furtif, qui souffle le mal dans les poitrines des hommes, qu'il soit djinn ou humain.\"",
      transliteration: "Qul a'oodhu birabbin-naas. Malikin-naas. Ilaahin-naas. Min sharril-waswaasil-khannaas. Alladhee yuwaswisu fee sudoorin-naas. Minal-jinnati wannaas.",
      reference: 'Coran 114:1-6',
      repetitions: 3,
    },
  ],
  forgiveness: [
    {
      id: 'forgiveness-1',
      category: 'forgiveness',
      title: 'Istighfar - Demande de pardon',
      arabicText: 'أَسْتَغْفِرُ اللَّهَ الْعَظِيمَ الَّذِي لَا إِلَهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ وَأَتُوبُ إِلَيْهِ',
      englishText: 'I seek the forgiveness of Allah the Mighty, whom there is none worthy of worship except Him, the Living, the Self-Sustaining, and I turn to Him in repentance.',
      frenchText: "Je demande pardon \u00e0 Allah le Magnifique, celui dont il n'y a de divinit\u00e9 digne d'adoration que Lui, le Vivant, le Subsistant, et je me repens \u00e0 Lui.",
      transliteration: "Astaghfirullaahal-'Adheem alladhee laa ilaaha illaa Huwal-Hayyul-Qayyoomu wa atoobu ilayh.",
      reference: 'Sunan Abu Dawud 1517',
      repetitions: 3,
    },
    {
      id: 'forgiveness-2',
      category: 'forgiveness',
      title: "Dou'a du repentir",
      arabicText: 'رَبِّ اغْفِرْ لِي وَتُبْ عَلَيَّ إِنَّكَ أَنْتَ التَّوَّابُ الرَّحِيمُ',
      englishText: 'My Lord, forgive me and accept my repentance. Indeed, You are the Accepting of Repentance, the Merciful.',
      frenchText: "Seigneur, pardonne-moi et accepte mon repentir. Certes, Tu es Celui qui accepte le repentir, le Mis\u00e9ricordieux.",
      transliteration: "Rabbighfir lee wa tub 'alayya innaka Antat-Tawwaabur-Raheem.",
      reference: 'Sunan at-Tirmidhi 3434',
      repetitions: 100,
    },
  ],
  daily: [
    {
      id: 'daily-1',
      category: 'daily',
      title: "Dou'a en sortant de la maison",
      arabicText: 'بِسْمِ اللَّهِ تَوَكَّلْتُ عَلَى اللَّهِ لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ',
      englishText: 'In the name of Allah, I place my trust in Allah, and there is no might or power except with Allah.',
      frenchText: "Au nom d'Allah, je place ma confiance en Allah, et il n'y a de force et de puissance qu'en Allah.",
      transliteration: "Bismillaahi tawakkaltu 'alallaahi laa hawla wa laa quwwata illaa billaah.",
      reference: 'Sunan Abu Dawud 5095',
      repetitions: 1,
    },
    {
      id: 'daily-2',
      category: 'daily',
      title: "Dou'a en entrant dans la maison",
      arabicText: 'بِسْمِ اللَّهِ وَلَجْنَا وَبِسْمِ اللَّهِ خَرَجْنَا وَعَلَى رَبِّنَا تَوَكَّلْنَا',
      englishText: 'In the name of Allah we enter and in the name of Allah we leave, and upon our Lord we place our trust.',
      frenchText: "Au nom d'Allah nous entrons et au nom d'Allah nous sortons, et en notre Seigneur nous pla\u00e7ons notre confiance.",
      transliteration: "Bismillaahi walajnaa, wa bismillaahi kharajnaa, wa 'alaa Rabbinaa tawakkalnaa.",
      reference: 'Sunan Abu Dawud 5096',
      repetitions: 1,
    },
    {
      id: 'daily-3',
      category: 'daily',
      title: "Dou'a en entrant aux toilettes",
      arabicText: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْخُبُثِ وَالْخَبَائِثِ',
      englishText: 'O Allah, I seek refuge in You from the male and female unclean spirits.',
      frenchText: "\u00d4 Allah, je cherche refuge aupr\u00e8s de Toi contre les mauvais esprits m\u00e2les et femelles.",
      transliteration: "Allaahumma innee a'oodhu bika minal-khubthi wal-khabaa'ith.",
      reference: 'Sahih al-Bukhari 142',
      repetitions: 1,
    },
  ],
  quran: [
    {
      id: 'quran-1',
      category: 'quran',
      title: "Dou'a d'ouverture du Coran",
      arabicText: 'اللَّهُمَّ انْفَعْنِي بِمَا عَلَّمْتَنِي وَعَلِّمْنِي مَا يَنْفَعُنِي وَزِدْنِي عِلْمًا',
      englishText: 'O Allah, benefit me with what You have taught me, teach me what will benefit me, and increase me in knowledge.',
      frenchText: "\u00d4 Allah, fais-moi tirer profit de ce que Tu m'as enseign\u00e9, enseigne-moi ce qui me sera utile et augmente-moi en science.",
      transliteration: "Allaahum-manfa'nee bimaa 'allamtanee wa 'allimnee maa yanfa'unee wa zidnee 'ilmaa.",
      reference: 'Sunan at-Tirmidhi 3599',
      repetitions: 1,
    },
    {
      id: 'quran-2',
      category: 'quran',
      title: "Dou'a pour la comprehension du Coran",
      arabicText: 'رَبِّ اشْرَحْ لِي صَدْرِي وَيَسِّرْ لِي أَمْرِي وَاحْلُلْ عُقْدَةً مِنْ لِسَانِي يَفْقَهُوا قَوْلِي',
      englishText: 'My Lord, expand for me my chest, ease my task for me, and remove the impediment from my speech so they may understand my words.',
      frenchText: "Seigneur, ouvre-moi ma poitrine, facilite-moi ma mission, et d\u00e9noue un noeud en ma langue afin qu'ils comprennent mes paroles.",
      transliteration: "Rabbish-rahlee sadree, wa yassir lee amree, wahlul 'uqdatam-mil-lisaanee yafqahoo qawlee.",
      reference: 'Coran 20:25-28',
      repetitions: 1,
    },
  ],
  rabbana: [
    {
      id: 'rabbana-1',
      category: 'rabbana',
      title: 'Rabbana - Bonte ici-bas et dans l\'au-dela',
      arabicText: 'رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ',
      englishText: 'Our Lord, give us in this world [that which is] good and in the Hereafter [that which is] good and protect us from the punishment of the Fire.',
      frenchText: "Notre Seigneur, accorde-nous belle part ici-bas, et belle part aussi dans l'au-del\u00e0 ; et prot\u00e8ge-nous du ch\u00e2timent du Feu.",
      transliteration: "Rabbanaa aatinaa fid-dunyaa hasanatan wa fil-aakhirati hasanatan wa qinaa 'adhaaban-naar.",
      reference: 'Coran 2:201',
      repetitions: 1,
    },
    {
      id: 'rabbana-2',
      category: 'rabbana',
      title: 'Rabbana - Patience et fermete',
      arabicText: 'رَبَّنَا أَفْرِغْ عَلَيْنَا صَبْرًا وَثَبِّتْ أَقْدَامَنَا وَانْصُرْنَا عَلَى الْقَوْمِ الْكَافِرِينَ',
      englishText: 'Our Lord, pour upon us patience and plant firmly our feet and give us victory over the disbelieving people.',
      frenchText: "Notre Seigneur, d\u00e9verse sur nous l'endurance, affermis nos pas et donne-nous la victoire sur les gens m\u00e9cr\u00e9ants.",
      transliteration: "Rabbanaa afrigh 'alaynaa sabran wa thabbit aqdaamanaa wansurnaa 'alal-qawmil-kaafireen.",
      reference: 'Coran 2:250',
      repetitions: 1,
    },
    {
      id: 'rabbana-3',
      category: 'rabbana',
      title: 'Rabbana - Ne nous charge pas',
      arabicText: 'رَبَّنَا لَا تُؤَاخِذْنَا إِنْ نَسِينَا أَوْ أَخْطَأْنَا رَبَّنَا وَلَا تَحْمِلْ عَلَيْنَا إِصْرًا كَمَا حَمَلْتَهُ عَلَى الَّذِينَ مِنْ قَبْلِنَا رَبَّنَا وَلَا تُحَمِّلْنَا مَا لَا طَاقَةَ لَنَا بِهِ وَاعْفُ عَنَّا وَاغْفِرْ لَنَا وَارْحَمْنَا أَنْتَ مَوْلَانَا فَانْصُرْنَا عَلَى الْقَوْمِ الْكَافِرِينَ',
      englishText: 'Our Lord, do not impose blame upon us if we have forgotten or erred. Our Lord, and lay not upon us a burden like that which You laid upon those before us. Our Lord, and burden us not with that which we have no ability to bear. And pardon us; and forgive us; and have mercy upon us. You are our protector, so give us victory over the disbelieving people.',
      frenchText: "Notre Seigneur, ne nous ch\u00e2tie pas si nous oublions ou si nous nous trompons. Notre Seigneur, ne nous charge pas d'un fardeau comme celui dont Tu as charg\u00e9 ceux qui v\u00e9curent avant nous. Notre Seigneur, ne nous impose pas ce que nous ne pouvons supporter. Efface nos fautes, pardonne-nous et fais-nous mis\u00e9ricorde. Tu es notre Ma\u00eetre, accorde-nous la victoire sur les gens m\u00e9cr\u00e9ants.",
      transliteration: "Rabbanaa laa tu'aakhidhnaa in naseenaa aw akhta'naa. Rabbanaa wa laa tahmil 'alaynaa isran kamaa hamaltahu 'alal-ladheena min qablinaa. Rabbanaa wa laa tuhammilnaa maa laa taaqata lanaa bih. Wa'fu 'annaa, waghfir lanaa, warhamnaa. Anta Mawlaanaa fansurnaa 'alal-qawmil-kaafireen.",
      reference: 'Coran 2:286',
      repetitions: 1,
    },
  ],
  misc: [
    {
      id: 'misc-1',
      category: 'misc',
      title: "Dou'a pour soulager l'angoisse",
      arabicText: 'لَا إِلَهَ إِلَّا اللَّهُ الْعَظِيمُ الْحَلِيمُ لَا إِلَهَ إِلَّا اللَّهُ رَبُّ الْعَرْشِ الْعَظِيمِ لَا إِلَهَ إِلَّا اللَّهُ رَبُّ السَّمَوَاتِ وَرَبُّ الأَرْضِ وَرَبُّ الْعَرْشِ الْكَرِيمِ',
      englishText: "None has the right to be worshipped except Allah, the Mighty, the Forbearing. None has the right to be worshipped except Allah, Lord of the Magnificent Throne. None has the right to be worshipped except Allah, Lord of the heavens, Lord of the earth, and Lord of the Noble Throne.",
      frenchText: "Nul ne m\u00e9rite d'\u00eatre ador\u00e9 sauf Allah, le Magnifique, l'Indulgent. Nul ne m\u00e9rite d'\u00eatre ador\u00e9 sauf Allah, le Seigneur du Tr\u00f4ne Magnifique. Nul ne m\u00e9rite d'\u00eatre ador\u00e9 sauf Allah, Seigneur des cieux, Seigneur de la terre et Seigneur du Tr\u00f4ne Noble.",
      transliteration: "Laa ilaaha illallaahul-'Adheemul-Haleem. Laa ilaaha illallaahu Rabbul-'Arshil-'Adheem. Laa ilaaha illallaahu Rabbus-samaawaati wa Rabbul-ardi wa Rabbul-'Arshil-Kareem.",
      reference: 'Sahih al-Bukhari 6346',
      repetitions: 1,
    },
    {
      id: 'misc-2',
      category: 'misc',
      title: "Dou'a en cas de difficulte",
      arabicText: 'اللَّهُمَّ لَا سَهْلَ إِلَّا مَا جَعَلْتَهُ سَهْلًا وَأَنْتَ تَجْعَلُ الْحَزْنَ إِذَا شِئْتَ سَهْلًا',
      englishText: 'O Allah, nothing is easy except what You make easy, and You make the difficult easy if it be Your Will.',
      frenchText: "\u00d4 Allah, rien n'est facile sauf ce que Tu rends facile, et Tu rends le difficile facile si Tu le veux.",
      transliteration: "Allaahumma laa sahla illaa maa ja'altahu sahlaa, wa Anta taj'alul-hazna idhaa shi'ta sahlaa.",
      reference: 'Ibn Hibban 2427',
      repetitions: 1,
    },
  ],
};

export function getFallbackDuas(category: string): Dua[] {
  return FALLBACK_DUAS[category] || [];
}
