/**
 * Utility to load and access scraped Duas.com category data.
 * Data is loaded from a static JSON file (data/duas-com-data.json)
 * that was generated by the scraper script (scripts/scrape-duas.js).
 */

export interface DuaLink {
  id: string;
  title: string;
  slug: string;
  url: string;
}

export interface DuasComCategory {
  id: string;
  name: string;
  slug: string;
  sourceUrl: string;
  duas: DuaLink[];
}

export interface LetterGroup {
  letter: string;
  categories: DuasComCategory[];
}

export interface DuasComData {
  scrapedAt: string;
  letters: LetterGroup[];
}

// Import the scraped JSON data
let _cachedData: DuasComData | null = null;

export function getDuasComData(): DuasComData {
  if (_cachedData) return _cachedData;

  try {
    // Use require for static JSON import (works in RN/Expo)
    const data = require('@/data/duas-com-data.json') as DuasComData;
    _cachedData = data;
    return data;
  } catch (error) {
    console.warn('Failed to load duas-com-data.json, using empty data:', error);
    // Return empty structure with all 26 letters
    const letters: LetterGroup[] = [];
    for (let i = 0; i < 26; i++) {
      letters.push({
        letter: String.fromCharCode(97 + i),
        categories: [],
      });
    }
    return { scrapedAt: '', letters };
  }
}

/**
 * Get all letter groups
 */
export function getAllLetterGroups(): LetterGroup[] {
  return getDuasComData().letters;
}

/**
 * Get categories for a specific letter
 */
export function getCategoriesForLetter(letter: string): DuasComCategory[] {
  const data = getDuasComData();
  const group = data.letters.find(l => l.letter === letter.toLowerCase());
  return group?.categories ?? [];
}

/**
 * Find a category by its slug
 */
export function getCategoryBySlug(slug: string): DuasComCategory | null {
  const data = getDuasComData();
  for (const group of data.letters) {
    const cat = group.categories.find(c => c.slug === slug);
    if (cat) return cat;
  }
  return null;
}

/**
 * Find a category by its ID
 */
export function getCategoryById(id: string): DuasComCategory | null {
  const data = getDuasComData();
  for (const group of data.letters) {
    const cat = group.categories.find(c => c.id === id);
    if (cat) return cat;
  }
  return null;
}

/**
 * Search categories by name
 */
export function searchCategories(query: string): DuasComCategory[] {
  if (!query.trim()) return [];
  const data = getDuasComData();
  const q = query.toLowerCase().trim();
  const results: DuasComCategory[] = [];

  for (const group of data.letters) {
    for (const cat of group.categories) {
      if (cat.name.toLowerCase().includes(q)) {
        results.push(cat);
      }
    }
  }

  return results;
}

/**
 * Get total counts
 */
export function getDataStats(): { totalCategories: number; totalDuas: number; activeLetters: number } {
  const data = getDuasComData();
  let totalCategories = 0;
  let totalDuas = 0;
  let activeLetters = 0;

  for (const group of data.letters) {
    if (group.categories.length > 0) activeLetters++;
    totalCategories += group.categories.length;
    for (const cat of group.categories) {
      totalDuas += cat.duas.length;
    }
  }

  return { totalCategories, totalDuas, activeLetters };
}

/**
 * Generate a slug from a category name
 */
export function generateSlug(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');
}
