/*
  # Insert complete 99 Names of Allah

  1. Updates
    - Insert all 99 Names of Allah with:
      - Arabic name
      - Transliteration
      - Meaning
      - Category
*/

-- Insert all 99 Names of Allah
INSERT INTO divine_names (name, transliteration, meaning, category) VALUES
  ('ٱللَّٰه', 'Allah', 'The Greatest Name', 'essence'),
  ('ٱلرَّحْمَٰن', 'Ar-Rahman', 'The Most Gracious', 'mercy'),
  ('ٱلرَّحِيم', 'Ar-Raheem', 'The Most Merciful', 'mercy'),
  ('ٱلْمَلِك', 'Al-Malik', 'The King/Sovereign', 'sovereignty'),
  ('ٱلْقُدُّوس', 'Al-Quddus', 'The Pure One', 'purity'),
  ('ٱلسَّلَام', 'As-Salam', 'The Source of Peace', 'peace'),
  ('ٱلْمُؤْمِن', 'Al-Mu''min', 'The Inspirer of Faith', 'faith'),
  ('ٱلْمُهَيْمِن', 'Al-Muhaymin', 'The Guardian', 'protection'),
  ('ٱلْعَزِيز', 'Al-Aziz', 'The Almighty', 'power'),
  ('ٱلْجَبَّار', 'Al-Jabbar', 'The Compeller', 'power'),
  ('ٱلْمُتَكَبِّر', 'Al-Mutakabbir', 'The Greatest', 'greatness'),
  ('ٱلْخَالِق', 'Al-Khaliq', 'The Creator', 'creation'),
  ('ٱلْبَارِئ', 'Al-Bari''', 'The Maker', 'creation'),
  ('ٱلْمُصَوِّر', 'Al-Musawwir', 'The Fashioner', 'creation'),
  ('ٱلْغَفَّار', 'Al-Ghaffar', 'The Perpetual Forgiver', 'forgiveness'),
  ('ٱلْقَهَّار', 'Al-Qahhar', 'The Subduer', 'power'),
  ('ٱلْوَهَّاب', 'Al-Wahhab', 'The Bestower', 'giving'),
  ('ٱلرَّزَّاق', 'Ar-Razzaq', 'The Provider', 'provision'),
  ('ٱلْفَتَّاح', 'Al-Fattah', 'The Opener', 'guidance'),
  ('ٱلْعَلِيم', 'Al-Alim', 'The All-Knowing', 'knowledge'),
  ('ٱلْقَابِض', 'Al-Qabid', 'The Constrictor', 'justice'),
  ('ٱلْبَاسِط', 'Al-Basit', 'The Expander', 'mercy'),
  ('ٱلْخَافِض', 'Al-Khafid', 'The Abaser', 'justice'),
  ('ٱلرَّافِع', 'Ar-Rafi', 'The Exalter', 'honor'),
  ('ٱلْمُعِزّ', 'Al-Mu''izz', 'The Honorer', 'honor'),
  ('ٱلْمُذِلّ', 'Al-Mudhill', 'The Humiliator', 'justice'),
  ('ٱلسَّمِيع', 'As-Sami', 'The All-Hearing', 'knowledge'),
  ('ٱلْبَصِير', 'Al-Basir', 'The All-Seeing', 'knowledge'),
  ('ٱلْحَكَم', 'Al-Hakam', 'The Judge', 'justice'),
  ('ٱلْعَدْل', 'Al-Adl', 'The Utterly Just', 'justice'),
  ('ٱلْلَّطِيف', 'Al-Latif', 'The Subtle One', 'kindness'),
  ('ٱلْخَبِير', 'Al-Khabir', 'The All-Aware', 'knowledge'),
  ('ٱلْحَلِيم', 'Al-Halim', 'The Forbearing', 'patience'),
  ('ٱلْعَظِيم', 'Al-Azim', 'The Magnificent', 'greatness'),
  ('ٱلْغَفُور', 'Al-Ghafur', 'The Forgiving', 'forgiveness'),
  ('ٱلشَّكُور', 'Ash-Shakur', 'The Appreciative', 'gratitude'),
  ('ٱلْعَلِيّ', 'Al-Ali', 'The Most High', 'greatness'),
  ('ٱلْكَبِير', 'Al-Kabir', 'The Great', 'greatness'),
  ('ٱلْحَفِيظ', 'Al-Hafiz', 'The Preserver', 'protection'),
  ('ٱلْمُقِيت', 'Al-Muqit', 'The Nourisher', 'provision'),
  ('ٱلْحَسِيب', 'Al-Hasib', 'The Reckoner', 'justice'),
  ('ٱلْجَلِيل', 'Al-Jalil', 'The Majestic', 'greatness'),
  ('ٱلْكَرِيم', 'Al-Karim', 'The Generous', 'giving'),
  ('ٱلرَّقِيب', 'Ar-Raqib', 'The Watchful', 'protection'),
  ('ٱلْمُجِيب', 'Al-Mujib', 'The Responsive', 'mercy'),
  ('ٱلْوَاسِع', 'Al-Wasi', 'The All-Encompassing', 'greatness'),
  ('ٱلْحَكِيم', 'Al-Hakim', 'The Wise', 'wisdom'),
  ('ٱلْوَدُود', 'Al-Wadud', 'The Most Loving', 'love'),
  ('ٱلْمَجِيد', 'Al-Majid', 'The Most Glorious', 'glory'),
  ('ٱلْبَاعِث', 'Al-Ba''ith', 'The Resurrector', 'power'),
  ('ٱلشَّهِيد', 'Ash-Shahid', 'The Witness', 'knowledge'),
  ('ٱلْحَقّ', 'Al-Haqq', 'The Truth', 'truth'),
  ('ٱلْوَكِيل', 'Al-Wakil', 'The Trustee', 'trust'),
  ('ٱلْقَوِيّ', 'Al-Qawi', 'The Strong', 'power'),
  ('ٱلْمَتِين', 'Al-Matin', 'The Firm', 'strength'),
  ('ٱلْوَلِيّ', 'Al-Wali', 'The Protecting Friend', 'protection'),
  ('ٱلْحَمِيد', 'Al-Hamid', 'The Praiseworthy', 'praise'),
  ('ٱلْمُحْصِي', 'Al-Muhsi', 'The Counter', 'knowledge'),
  ('ٱلْمُبْدِئ', 'Al-Mubdi', 'The Originator', 'creation'),
  ('ٱلْمُعِيد', 'Al-Mu''id', 'The Restorer', 'creation'),
  ('ٱلْمُحْيِي', 'Al-Muhyi', 'The Giver of Life', 'life'),
  ('ٱلْمُمِيت', 'Al-Mumit', 'The Bringer of Death', 'death'),
  ('ٱلْحَيّ', 'Al-Hayy', 'The Ever-Living', 'life'),
  ('ٱلْقَيُّوم', 'Al-Qayyum', 'The Self-Subsisting', 'existence'),
  ('ٱلْوَاجِد', 'Al-Wajid', 'The Finder', 'perfection'),
  ('ٱلْمَاجِد', 'Al-Majid', 'The Noble', 'glory'),
  ('ٱلْوَاحِد', 'Al-Wahid', 'The One', 'unity'),
  ('ٱلصَّمَد', 'As-Samad', 'The Eternal', 'perfection'),
  ('ٱلْقَادِر', 'Al-Qadir', 'The Able', 'power'),
  ('ٱلْمُقْتَدِر', 'Al-Muqtadir', 'The Powerful', 'power'),
  ('ٱلْمُقَدِّم', 'Al-Muqaddim', 'The Expediter', 'decree'),
  ('ٱلْمُؤَخِّر', 'Al-Mu''akhkhir', 'The Delayer', 'decree'),
  ('ٱلْأَوَّل', 'Al-Awwal', 'The First', 'time'),
  ('ٱلْآخِر', 'Al-Akhir', 'The Last', 'time'),
  ('ٱلظَّاهِر', 'Az-Zahir', 'The Manifest', 'existence'),
  ('ٱلْبَاطِن', 'Al-Batin', 'The Hidden', 'existence'),
  ('ٱلْوَالِي', 'Al-Wali', 'The Governor', 'sovereignty'),
  ('ٱلْمُتَعَالِي', 'Al-Muta''ali', 'The Most Exalted', 'greatness'),
  ('ٱلْبَرّ', 'Al-Barr', 'The Source of Goodness', 'goodness'),
  ('ٱلتَّوَّاب', 'At-Tawwab', 'The Ever-Returning', 'forgiveness'),
  ('ٱلْمُنْتَقِم', 'Al-Muntaqim', 'The Avenger', 'justice'),
  ('ٱلْعَفُوّ', 'Al-Afuw', 'The Pardoner', 'forgiveness'),
  ('ٱلرَّؤُوف', 'Ar-Ra''uf', 'The Kind', 'kindness'),
  ('مَالِكُ ٱلْمُلْك', 'Malik-ul-Mulk', 'Owner of All Sovereignty', 'sovereignty'),
  ('ذُو ٱلْجَلَالِ وَٱلْإِكْرَام', 'Dhul-Jalali-wal-Ikram', 'Lord of Majesty and Generosity', 'greatness'),
  ('ٱلْمُقْسِط', 'Al-Muqsit', 'The Equitable', 'justice'),
  ('ٱلْجَامِع', 'Al-Jami', 'The Gatherer', 'unity'),
  ('ٱلْغَنِيّ', 'Al-Ghani', 'The Self-Sufficient', 'perfection'),
  ('ٱلْمُغْنِي', 'Al-Mughni', 'The Enricher', 'giving'),
  ('ٱلْمَانِع', 'Al-Mani', 'The Preventer', 'protection'),
  ('ٱلضَّارّ', 'Ad-Darr', 'The Distresser', 'decree'),
  ('ٱلنَّافِع', 'An-Nafi', 'The Benefiter', 'mercy'),
  ('ٱلنُّور', 'An-Nur', 'The Light', 'guidance'),
  ('ٱلْهَادِي', 'Al-Hadi', 'The Guide', 'guidance'),
  ('ٱلْبَدِيع', 'Al-Badi', 'The Originator', 'creation'),
  ('ٱلْبَاقِي', 'Al-Baqi', 'The Everlasting', 'existence'),
  ('ٱلْوَارِث', 'Al-Warith', 'The Inheritor', 'existence'),
  ('ٱلرَّشِيد', 'Ar-Rashid', 'The Guide to the Right Path', 'guidance'),
  ('ٱلصَّبُور', 'As-Sabur', 'The Patient', 'patience')
ON CONFLICT (name) DO NOTHING;